### ISSUE TITLE
Keep getting "Segmentation fault (core dumped)" error for various lattice configuration of ipglasma input file.

### ISSUE THREAD

**Issue by nikhilhatwar** [KMPST/KoMPoST#1]
Dear Sir,

I am trying to use KoMPoST with an ipglasma input file for PbPb 2760 GeV system. Example input file is attached here.
[input_2760PbPb.txt](https://github.com/KMPST/KoMPoST/files/6963833/input_2760PbPb.txt)

This file produces the following "energy momentum tensor input file for KoMPoST".

[Tmunu-t0p0984375-0.txt](https://github.com/KMPST/KoMPoST/files/6963863/Tmunu-t0p0984375-0.txt)
[setup.txt](https://github.com/KMPST/KoMPoST/files/6963949/setup.txt)

Using this file as KoMPoST input in the "setup" file(also attached), I get an error "Segmentation fault (core dumped)". I tried varying the lattice sizes, but this error persists.
Please suggest a solution.

Also a minor correction: The first line in setup.ini is [KoMPoST_IO]. Maybe it should be [KoMPoSTInputs], otherwise the code doesn't run.

**Comment by nikhilhatwar** [comment]
Deleting the first line with comments in the "Energy momentum tensor file" of IP Glasma worked. Forgive me for bothering.

**Comment by j-f-paquet** [comment]
Dear Nikhil,

Apologies for the slow reply, we hadn't had a chance to look at this yet. Happy to hear the issue is resolved. We'll fix this in the repository as well, thanks for letting us know.

All the best,

J-F
