### ISSUE TITLE
Doubt about low value of energy density in KoMPoST output file

### ISSUE THREAD

**Issue by nikhilhatwar** [KMPST/KoMPoST#2]
Dear Sir,

I am trying to use KoMPoST code for a study.
From what I could understand, energy density (in GeV/fm^3 units) is being saved in the third column of "OutputFileTag" file.

I have tried using the  IP-Glasma input file ([input_2760PbPb.txt](https://github.com/KMPST/KoMPoST/files/7007210/input_2760PbPb.txt)) to generate "T_munu input file for KoMPoST", but I did not get large enough value of energy density to run hydro using the output from KoMPoST. The max energy density value near (0,0) coordinate remained near 200 GeV / fm^3.
Whereas the max energy density value in the IP-Glasma's "energy momentum tensor" file is around 1800 GeV / fm^3.
The KoMPoST parameters that I used are in [setup.txt](https://github.com/KMPST/KoMPoST/files/7009839/setup.txt).

Could you please tell me if I am using a wrong parameter somewhere, OR if,
it is required to scale up the KoMPoST output energy density distribution to match with the experimental values before using it to run hydro?

**Comment by nikhilhatwar** [comment]
Forgive me, again.
I wrongly formatted the KoMPoST output file before using it hydro.
After correcting it, I am able to run hydro with KoMPoST for satisfactory duration.

**Comment by j-f-paquet** [comment]
Dear Nikhil,

Thank you for the update.

Best,

J-F
